<?php

/**
 * @file
 * Install, update and uninstall functions for the writing365 module.
 */

/**
 * Implements hook_install().
 */
function writing365_install() {
  // Ensure the writing365 node type is available.
  node_types_rebuild();
  $types = node_type_get_types();
  node_add_body_field($types['writing365']);
}

/**
 * Implements hook_uninstall().
 */
function writing365_uninstall() {
  variable_del('writing360_block_count');
}
